branch-defaults:
  dev:
    environment: EngineeringFullStackAppsInCloud-dev
    group_suffix: null
  master:
    environment: EngineeringFullStackAppsInCloud-prod
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  udagram-filter-dev:
    branch: null
    repository: null
global:
  application_name: EngineeringFullStackAppsInCloud
  branch: null
  default_ec2_keyname: fullstackappdev
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application